[package]
name = "xpsimport"
version = "0.1.0"
authors = ["crystalboxes <crystalboxesgfx@gmail.com>"]
edition = "2018"

[lib]
name = "xpsimport"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
byteorder = "1"
libc = "0.2"
